### ISSUE TITLE
Investigate different input validation rule support

### ISSUE THREAD

**Issue by RoussKS** [upmind-automation/provision-provider-base#12]
Currently the base library (and all dependents) relies on Laravel validation rule.

While that is not an issue itself, the use of Laravel Facades, blocks adding pure Unit Tests on some Providers, as an error `RuntimeException: A facade root has not been set.` is thrown from the `\Upmind\ProvisionBase\Provider\DataSet\RuleParser::getValidator()`.

Investigate & discuss options
- Avoid use of Facades, maybe load the Validation Factory (which the Facade triggers) via the constructor of the relevant methods
- Use of a different library like [Respect\Validation](https://github.com/Respect/Validation)

**Comment by uphlewis** [comment]
If we have a Validator factory we can set statically on DataSet (e.g., `DataSet::setValidatorFactory()`), then we can remove use of the Validator:: facade. 

Use of a different library would be too big of a breaking change

**Comment by RoussKS** [comment]
Maybe dupe of #50

**Comment by uphlewis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Provision Base library - Decouple Laravel Facade Validator Factory](https://trello.com/c/Oyjg37un/11-provision-base-library-decouple-laravel-facade-validator-factory)
