### ISSUE TITLE
Readme and composer.json

### ISSUE THREAD

**Issue by OlegBodyansky** [upmind-automation/provision-provider-base#5]
I have found that readme has a string  `composer require upmind/provision-provider-shared-hosting` 
but composer.json is "name": "upmind/provision-provider-base",

**Comment by uphlewis** [comment]
Oops! Thanks for pointing that out Oleg. 🙂

Documentation and help guides around developing with the Upmind provision system are still a work in progress, so if you'd like to discuss your use case or have any questions in general, let me know!
